version: "3.8"

services:
  app:
    build: .
    container_name: fb_comment_responder
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: flask run